### ISSUE TITLE
can not work for command line "bundle exec jekyll build"

### ISSUE THREAD

**Issue by lixingguang** [blab/blotter#12]
@trvrb I want to use blotter to build my website, and when I run the command line "bundle exec jekyll build",
it reports to me 👍:
lixingguangtekiMacBook-puro:blotter lixingguang$ bundle exec jekyll build
Configuration file: /Users/lixingguang/blotter/_config.yml
            Source: /Users/lixingguang/blotter
       Destination: /Users/lixingguang/blotter/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Warning: parse error in /Users/lixingguang/blotter/_site/talks/reveal-v2/css/print/pdf.css. Don't panic - copying initial file
Details: parse error on value "@page " (error)
Warning: parse error in /Users/lixingguang/blotter/_site/talks/reveal-v2/css/theme/default.css. Don't panic - copying initial file
Details: parse error on value ":not(" (error)
Warning: parse error in /Users/lixingguang/blotter/_site/talks/reveal-v2/css/theme/trvrb.css. Don't panic - copying initial file
Details: parse error on value ":not(" (error)
Warning: parse error in /Users/lixingguang/blotter/_site/talks/reveal-v3/css/reveal.css. Don't panic - copying initial file
Details: parse error on value ":not(" (error)
                    done in 11.747 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

**Comment by tsibley** [comment]
Though ideally these warnings wouldn't happen, they are completely ignoreable and shouldn't break the site build.
