### ISSUE TITLE
The tag `eqinline` is not a recognized Liquid Tag

### ISSUE THREAD

**Issue by tarunaaggarwal** [blab/blotter#2]
Hello. I am trying to customize your site's layout for our own lab site and have successfully forked the repo into my directory. I am able to build the site locally with Jekyll but I keep getting the error below from Github when building the live site. I have tried to fix this error by deleting files but that is not working. More files keep popping up with this error. Do you have any suggestions please? Thank you!

```The tag `eqinline` on line 189 in `guide/_posts/2013-10-26-style.md` is not a recognized Liquid tag.```

**Comment by trvrb** [comment]
This is a custom Liquid tag provided by the plugin here: https://github.com/blab/blotter/blob/master/_plugins/eqinline.rb. This is used for equation display.

GitHub Pages doesn't allow any custom plugins. Hence the error.

You can either host yourself on Amazon S3 or remove all references to `eqinline` and the other custom plugins. Good luck!

**Comment by trvrb** [comment]
Closing this now @tarunaaggarwal. Reopen if you run into additional difficulties with this.
