### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by rica01** [blab/blotter#31]
Hello. Thanks for your website, its an amazing system! :D

Tiny question: the default font doenst render turkish characters very well, is there an easy way to change it?

**Comment by trvrb** [comment]
Hi @rica01. Sorry, I just noticed this issue years later. Fonts on the website are a bit of a throw back. I'm using Adobe Fonts to provide Museo Sans. If you wanted to use this exact strategy, but with a different font, you'd need to register for your own Adobe Fonts account and then swap in your own project ID here: https://github.com/blab/blotter/blob/master/_layouts/default.html#L18. Alternatively, you could use Google Fonts, which is what I do for the slides in Reveal.js: https://github.com/blab/blotter/blob/master/talks/reveal-v4/dist/theme/blotter.css#L5. Hope this might still be helpful.
